<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
      
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Website</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.8.4/swiper-bundle.min.css">
    <link rel="stylesheet" href="css/style.css">

</head>
<div class="content">
  

<p>
            Welcome
            <strong>
                <?php echo $_SESSION['username']; ?>
            </strong>
        </p>

<header class="banner" id="mainHeader" role="banner">

    <nav role="navigation">
        <div class="top-header">
            <div class="navBurger">
                <div class="burger"></div>
            </div>
        </div>
 
<!-- This part is the navigation generated by Wordpress.  -->
        <ul id="menu-vertical-menu" class="nav">
            <li><a href="#">Combo</a></li>
            <li><a href="#">Special</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Option</a></li>
		</ul>
    </nav>
    
</header>
<body>
    <div class="swiper-container entree">
        <div class="swiper-wrapper">
            <!-- We need to add the Id text to be able to use the class and it's attributes -->
            <div class="swiper-slide" id = "burrito">
                <!-- <h1>Slide 1</h1> -->
                  <img class="card-image" src="img/burrito.jpg" />
                  <div class="card-columns">
                    <div class="cals text-left">750 Cals</div>
                    <div class="card-name text-center">Burrito</div>
                    <div class="price text-right">$4.99</div>
                  </div>
            </div>

            <div class="swiper-slide">
                <!-- <h1>Slide 2</h1> -->
                <img class="card-image" src="img/fajitas.jpg" />
                <div class="card-columns">
                  <div class="cals text-left">750 Cals</div>
                  <div class="card-name text-center">Fajitas</div>
                  <div class="price text-right">$4.99</div>
                </div>
            </div>
            <div class="swiper-slide">
                <!-- <h1>Slide 3</h1> -->
                <img class="card-image" src="img/enchilada.jpg" />
                <div class="card-columns">
                  <div class="cals text-left">750 Cals</div>
                  <div class="card-name text-center">Enchiladas</div>
                  <div class="price text-right">$4.99</div>
                </div>
            </div>
            <div class="swiper-slide">
                <!-- <h1>Slide 3</h1> -->
                <img class="card-image" src="img/chile verde.jpg" />
                <div class="card-columns">
                  <div class="cals text-left">750 Cals</div>
                  <div class="card-name text-center">Chile Verde</div>
                  <div class="price text-right">$4.99</div>
                </div>
            </div>
            <div class="swiper-slide">
                <!-- <h1>Slide 3</h1> -->
                <img class="card-image" src="img/taco.jpg" />
                <div class="card-columns">
                  <div class="cals text-left">750 Cals</div>
                  <div class="card-name text-center">Taco</div>
                  <div class="price text-right">$4.99</div>
                </div>
            </div>
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
    <!-- End of first slider, Entree -->
    <div class="swiper-container appetizer">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <!-- <h1>Slide 1</h1> -->
                  <img class="card-image" src="img/nacho.jpg" />
                  <div class="card-columns">
                    <div class="cals text-left">750 Cals</div>
                    <div class="card-name text-center">Nachos</div>
                    <div class="price text-right">$4.99</div>
                  </div>
            </div>
            <div class="swiper-slide">
                <h1>Slide 2</h1>
            </div>
            <div class="swiper-slide">
                <h1>Slide 3</h1>
            </div>
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
    <!-- End of Second slider, appetizer -->
    <div class="swiper-container dessert">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <!-- <h1>Slide 1</h1> -->
                  <img class="card-image" src="img/churros.jpg" />
                  <div class="card-columns">
                    <div class="cals text-left">750 Cals</div>
                    <div class="card-name text-center">Churros</div>
                    <div class="price text-right">$4.99</div>
                  </div>
            </div>
            <div class="swiper-slide">
                <h1>Slide 2</h1>
            </div>
            <div class="swiper-slide">
                <h1>Slide 3</h1>
            </div>
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
     <!-- End of third slider, Dessert-->
    <div class="swiper-container beverage">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <!-- <h1>Slide 1</h1> -->
                  <img class="card-image" src="img/margarita.jpg" />
                  <div class="card-columns">
                    <div class="cals text-left">750 Cals</div>
                    <div class="card-name text-center">Margarita</div>
                    <div class="price text-right">$4.99</div>
                  </div>
            </div>
            <div class="swiper-slide">
                <h1>Slide 2</h1>
            </div>
            <div class="swiper-slide">
                <h1>Slide 3</h1>
            </div>
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
     <!-- End of fouth slider, Drinks -->
     <div class = "Cart" id="Cart"> 


     
     </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.8.4/swiper-bundle.min.js"></script>
<script src="src/slider.js"></script>
</html>